Allow gitgo-write to specify mode

diff --git a/bin/gitgo-write b/bin/gitgo-write
--- a/bin/gitgo-write
+++ b/bin/gitgo-write
@@ -1,7 +1,7 @@
 #!/bin/bash
 ############################################################################
 usage="\
-usage: gitgo-write [-a ATTACHMENT...] [-b BRANCH] [-h] [-t TAG...] [THREAD...]
+usage: gitgo-write [-a ATTACHMENT...] [-b BRANCH] [-h] [-m MODE] [-t TAG...] [THREAD...]
 
   Writes a message to the 'gitgo' branch to the specified threads. If the
   branch does not exist, it will be created.
@@ -18,6 +18,7 @@ options:
         -a    attachment files
         -b    the storage branch (default 'gitgo')
         -h    prints this help
+        -m    linkage mode (add, update, delete)
         -t    specify tags
 
 "
@@ -27,13 +28,20 @@ attachments=""
 branch="gitgo"
 tags=""
 mode="+"
-while getopts "a:b:ht:" option
+while getopts "a:b:hm:t:" option
 do
   case $option in
     a  )  attachments="${attachments}${OPTARG}\n" ;;
     b  )  branch="$OPTARG" ;;
     h  )  printf "$usage"
           exit 0 ;;
+    m  )  case $OPTARG in
+            add    )  mode="+" ;;
+            delete )  mode="-" ;;
+            update )  mode="~" ;;
+            \?     )  printf "invalid mode: $OPTARG" 
+                      exit 1 ;;
+          esac ;;
     t  )  tags="${tags}${OPTARG}\n" ;;
     \? )  printf "$usage" | head -n 1
           exit 2 ;;
